### ISSUE TITLE
Problema di installazione lavatrice 

### ISSUE THREAD

**Issue by redstyle82** [jumping2000/ha-packages#3]
Ciao! Ho un problema cercando di installare il tuo plugin. Dopo aver inserito tutti i file necessari nella directory di home assistant ed aver aggiunto tutte le entità obbligatorie nel blueprint del progetto, quando vado a salvare mi da questo errore Message malformed: Unable to determine action @ data['action'][0] hai idea di come possa risolvere? Grazie mille

**Comment by redstyle82** [comment]
Inoltre cercando di inserire la card versione STORAGE, ho questo errore: ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'state') in 'if (states['switch.plug_lavatrice'].state== 'on') return "#27b376"; return "#bf212f";'

**Comment by jumping2000** [comment]
devi personalizzare  le entità come già detto su gruppo supporto: "switch.plug_lavatrice"
