### ISSUE TITLE
[BUG] An FTTC parameter is maintained on FTTH

### ISSUE THREAD

**Issue by anto294** [jumping2000/ha-packages#4]
Hello,
the following code is kept on network.yaml after the python script, it causes errors of the underlying sensors templates. (Sensors fritz_upload_throughput & fritz_download_throughput not avaible)
FTTH Connection.

```
      # CHANGE THE SENSOR WITH YOURS
      - name: VDSL distance
        state: >
          {% set value = 'TAG_18' %}
          {{ (states(value)|float(default=0)/(13.81*sqrt(4.15))*1000) | round(0) }}
        unit_of_measurement: m
        state_class: measurement
        availability: >
          {{ states('TAG_18') not in ['unavailable', 'unknown', 'None']  }}
```

removed by hand, everything works perfectly.

**Comment by jumping2000** [comment]
It's not a bug, as I said in the documentation:

- "Ovviamente alcuni valori (come rumore ed attenuazione) non hanno senso se parliamo di connessioni [FTTH](https://it.wikipedia.org/wiki/FTTx) ma solo per connessioni [ADSL](https://it.wikipedia.org/wiki/ADSL) / [FTTC](https://it.wikipedia.org/wiki/FTTx)."
- NOTA: La card prevede gli elementi grafici per tutte le integrazioni (Speedtest, Adguard, Fritz), nel caso ad esempio non si voglia usare Speedtest occorre cancellare a mano dalla card tutta la parte relativa. E' consigliabile effettuare l'operazione subito dopo aver lanciato lo script di autoconfigurazione.
- Per il calcolo della distanza dal cabinet nel caso di connettività basta su FTTC - VDSL2 riportiamo di seguito la formula utilizzata:

**Comment by jumping2000** [comment]
closed, it's not a bug

**Comment by anto294** [comment]
Salve,
scrivo direttamente in Italiano, così faccio prima.
Intanto complimenti, bel lavoro!

Sono riuscito a cavarmela ad occhi chiusi, ma dato che è automatizzato benissimo, è un peccato questa svista.
Quel parametro VDSL permane su packages/elettrodomestici/network.yaml; oltre che nella card sotto il browser-mod "info".
Tutto il resto viene escluso correttamente, snr attenuazione etc.
Nella mia installazione, HA tronca tutta la sezione "template:" se non tolgo quella parte, impedendo la generazione di sensor.fritz_upload e download.
Persino i log si riempiono di errori in merito.

Se non ci sono altre segnalazioni in meritò, avrò qualche pkg fatto da me in conflitto.

**Comment by jumping2000** [comment]
> Salve, scrivo direttamente in Italiano, così faccio prima. Intanto complimenti, bel lavoro!
> 
> Sono riuscito a cavarmela ad occhi chiusi, ma dato che è automatizzato benissimo, è un peccato questa svista. Quel parametro VDSL permane su packages/elettrodomestici/network.yaml; oltre che nella card sotto il browser-mod "info". Tutto il resto viene escluso correttamente, snr attenuazione etc. Nella mia installazione, HA tronca tutta la sezione "template:" se non tolgo quella parte, impedendo la generazione di sensor.fritz_upload e download. Persino i log si riempiono di errori in merito.
> 
> Se non ci sono altre segnalazioni in meritò, avrò qualche pkg fatto da me in conflitto.

grazie per i complimenti, ma andiamo al nocciolo:
il package è fatto in maniera generale sia per connessioni FTTH che FTTC, il sensore VDSL distance ovviamente funziona solo con connessioni FTTC.
Fare in modo di cancellare il sensore VDSL in automatico se la connessione è in FTTH, secondo me non ne vale la pena e renderebbe lo script adattato solo a questo package (e card)  e non universale come è ora, tanto che a breve rilascerò altri packages autoconfiguranti.
Quindi per me la soluzione  è che l'utente, **come suggerito nella documentazione**, controlli che packages e card non  abbiano elementi non gestiti. La procedura è piuttosto semplice e l'ho già inserita siu github, si tratta solo di aprire un editor, lanciare un "trova" e cancellare qualche riga, non mi sembra una cosa impossibile.

spero di averti risposto. ciao

**Comment by anto294** [comment]
Grazie per la risposta :)
La speranze è di non trovare il gruppo HA Italia pieno con lo stesso problema, essendo molto attivo mi sparerei xD
