### ISSUE TITLE
Errore con la card

### ISSUE THREAD

**Issue by RP92** [jumping2000/ha-packages#5]
Salve, ho seguito la guida per Router lo script sembra che vada a buon fine ma quando aggiungo la Modalità UI storage mi da questo errore 

ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'state') in 'if (states['TAG_08'].state== 'on')
    return "#27b376";
  return "#bf212f";'
  
[https://imgur.com/a/DoH5bz7](url)

**Qui sotto output auto_config.py -v**

` packages python autoconfig_x86_64/auto_config.py -v
{'verbose': True, 'automation_path': None, 'package_path': None, 'card_path': No                                                                                                                                                             ne, 'keys_path': None}

Key 'throughput_upload' found in blueprint dict. Value: sensor.speedtest_upload
Key 'throughput_download' found in blueprint dict. Value: sensor.speedtest_downl                                                                                                                                                             oad
Key 'external_ip' found in blueprint dict. Value: sensor.fritz_box_7590_ip_ester                                                                                                                                                             no
Key 'speedtest_ping' found in blueprint dict. Value: sensor.speedtest_ping
Key 'connection_status' found in blueprint dict. Value: binary_sensor.fritz_box_                                                                                                                                                             7590_collegamento
Key 'link_status' found in blueprint dict. Value: binary_sensor.fritz_box_7590_c                                                                                                                                                             ollegamento
Key 'connection_uptime' found in blueprint dict. Value: sensor.fritz_box_7590_te                                                                                                                                                             mpo_di_attivita_della_connessione
Key 'device_uptime' found in blueprint dict. Value: sensor.fritz_box_7590_tempo_                                                                                                                                                             di_attivita_della_connessione
Key 'switch_wifi_24' found in blueprint dict. Value: switch.fritz_box_7590_wi_fi                                                                                                                                                             _fritz_box_7590_2_4ghz
Key 'switch_wifi_5' found in blueprint dict. Value: switch.fritz_box_7590_wi_fi_                                                                                                                                                             fritz_box_7590_5ghz
Key 'switch_wifi_guest' found in blueprint dict. Value: switch.fritz_box_7590_wi                                                                                                                                                             _fi_fritz_box_accesso_ospite
Key 'upload_throughput' found in blueprint dict. Value: sensor.fritz_box_7590_ve                                                                                                                                                             locita_massima_di_caricamento_della_connessione
Key 'download_throughput' found in blueprint dict. Value: sensor.fritz_box_7590_                                                                                                                                                             velocita_massima_di_scaricamento_della_connessione
Key 'upload_link_throughput' found in blueprint dict. Value: sensor.fritz_box_75                                                                                                                                                             90_velocita_massima_di_caricamento_della_connessione
Key 'download_link_throughput' found in blueprint dict. Value: sensor.fritz_box_                                                                                                                                                             7590_velocita_massima_di_scaricamento_della_connessione
Key 'upload_noise_margin' found in blueprint dict. Value: sensor.fritz_repeater_                                                                                                                                                             2400_ultimo_riavvio
Key 'download_noise_margin' found in blueprint dict. Value: sensor.fritz_repeate                                                                                                                                                             r_2400_ultimo_riavvio
Key 'upload_power_attenuation' found in blueprint dict. Value: sensor.fritz_repe                                                                                                                                                             ater_2400_ultimo_riavvio
Key 'download_power_attenuation' found in blueprint dict. Value: sensor.fritz_re                                                                                                                                                             peater_2400_ultimo_riavvio
Key 'upload_gb_sent' found in blueprint dict. Value: sensor.fritz_box_7590_gb_in                                                                                                                                                             viati
Key 'download_gb_received' found in blueprint dict. Value: sensor.fritz_box_7590                                                                                                                                                             _gb_ricevuti
Key 'button_cleanup' found in blueprint dict. Value: button.fritz_box_7590_puliz                                                                                                                                                             ia
Key 'button_firmware_update' found in blueprint dict. Value: button.fritz_box_75                                                                                                                                                             90_aggiornamento_del_firmware
Key 'button_reboot' found in blueprint dict. Value: button.fritz_box_7590_riavvi                                                                                                                                                             o
Key 'button_reconnect' found in blueprint dict. Value: button.fritz_box_7590_ric                                                                                                                                                             onnetti
Key 'update_firmware' found in blueprint dict. Value: update.fritz_box_7590_frit                                                                                                                                                             z_os

List of entities: ['sensor.speedtest_upload', 'sensor.speedtest_download', 'sens                                                                                                                                                             or.fritz_box_7590_ip_esterno', 'sensor.speedtest_ping', 'binary_sensor.fritz_box                                                                                                                                                             _7590_collegamento', 'binary_sensor.fritz_box_7590_collegamento', 'sensor.fritz_                                                                                                                                                             box_7590_tempo_di_attivita_della_connessione', 'sensor.fritz_box_7590_tempo_di_a                                                                                                                                                             ttivita_della_connessione', 'switch.fritz_box_7590_wi_fi_fritz_box_7590_2_4ghz',                                                                                                                                                              'switch.fritz_box_7590_wi_fi_fritz_box_7590_5ghz', 'switch.fritz_box_7590_wi_fi                                                                                                                                                             _fritz_box_accesso_ospite', 'sensor.fritz_box_7590_velocita_massima_di_caricamen                                                                                                                                                             to_della_connessione', 'sensor.fritz_box_7590_velocita_massima_di_scaricamento_d                                                                                                                                                             ella_connessione', 'sensor.fritz_box_7590_velocita_massima_di_caricamento_della_                                                                                                                                                             connessione', 'sensor.fritz_box_7590_velocita_massima_di_scaricamento_della_conn                                                                                                                                                             essione', 'sensor.fritz_repeater_2400_ultimo_riavvio', 'sensor.fritz_repeater_24                                                                                                                                                             00_ultimo_riavvio', 'sensor.fritz_repeater_2400_ultimo_riavvio', 'sensor.fritz_r                                                                                                                                                             epeater_2400_ultimo_riavvio', 'sensor.fritz_box_7590_gb_inviati', 'sensor.fritz_                                                                                                                                                             box_7590_gb_ricevuti', 'button.fritz_box_7590_pulizia', 'button.fritz_box_7590_a                                                                                                                                                             ggiornamento_del_firmware', 'button.fritz_box_7590_riavvio', 'button.fritz_box_7                                                                                                                                                             590_riconnetti', 'update.fritz_box_7590_fritz_os']
Tags to replace with entities: {'TAG_00': 'sensor.speedtest_upload', 'TAG_01': '                                                                                                                                                             sensor.speedtest_download', 'TAG_02': 'sensor.fritz_box_7590_ip_esterno', 'TAG_0                                                                                                                                                             3': 'sensor.speedtest_ping', 'TAG_04': 'binary_sensor.fritz_box_7590_collegament                                                                                                                                                             o', 'TAG_05': 'binary_sensor.fritz_box_7590_collegamento', 'TAG_06': 'sensor.fri                                                                                                                                                             tz_box_7590_tempo_di_attivita_della_connessione', 'TAG_07': 'sensor.fritz_box_75                                                                                                                                                             90_tempo_di_attivita_della_connessione', 'TAG_08': 'switch.fritz_box_7590_wi_fi_                                                                                                                                                             fritz_box_7590_2_4ghz', 'TAG_09': 'switch.fritz_box_7590_wi_fi_fritz_box_7590_5g                                                                                                                                                             hz', 'TAG_10': 'switch.fritz_box_7590_wi_fi_fritz_box_accesso_ospite', 'TAG_11':                                                                                                                                                              'sensor.fritz_box_7590_velocita_massima_di_caricamento_della_connessione', 'TAG                                                                                                                                                             _12': 'sensor.fritz_box_7590_velocita_massima_di_scaricamento_della_connessione'                                                                                                                                                             , 'TAG_13': 'sensor.fritz_box_7590_velocita_massima_di_caricamento_della_conness                                                                                                                                                             ione', 'TAG_14': 'sensor.fritz_box_7590_velocita_massima_di_scaricamento_della_c                                                                                                                                                             onnessione', 'TAG_15': 'sensor.fritz_repeater_2400_ultimo_riavvio', 'TAG_16': 's                                                                                                                                                             ensor.fritz_repeater_2400_ultimo_riavvio', 'TAG_17': 'sensor.fritz_repeater_2400                                                                                                                                                             _ultimo_riavvio', 'TAG_18': 'sensor.fritz_repeater_2400_ultimo_riavvio', 'TAG_19                                                                                                                                                             ': 'sensor.fritz_box_7590_gb_inviati', 'TAG_20': 'sensor.fritz_box_7590_gb_ricev                                                                                                                                                             uti', 'TAG_21': 'button.fritz_box_7590_pulizia', 'TAG_22': 'button.fritz_box_759                                                                                                                                                             0_aggiornamento_del_firmware', 'TAG_23': 'button.fritz_box_7590_riavvio', 'TAG_2                                                                                                                                                             4': 'button.fritz_box_7590_riconnetti', 'TAG_25': 'update.fritz_box_7590_fritz_o                                                                                                                                                             s'}

Replacing...
Nothing to do with /config/packages/elettrodomestici/network.yaml

Replacing...
Nothing to do with /config/lovelace/card_elettrodomestici/card_router.yaml
`

**Comment by jumping2000** [comment]
Se ti dice "nothing to do" vuol dire che hai già lanciato lo script e sostituito i TAG.
Parti da una situazione pulita, cancella tutto quanto scaricato e poi inserisci i file **come da guida**:

- la cartella autoconfig e keys_network.txt in packages
- network.yaml in packages/elettrodomestici
- card_router.yaml in lovelace/card_elettrodomestici

lancia i comandi per x86 o rpi:

```
/config/packages# chmod 744 autoconfig_x86_64/auto_config.py
/config/packages# python autoconfig_x86_64/auto_config.py -v
```

e poi fai uno screenshoot del risultato.

**Comment by jumping2000** [comment]
> 

cmq hai scritto male il senosre nel blueprint, c'è uno spazio:  **sensor.fritz_box_75 90_tempo_di_attivita_della_connessione**

**Comment by RP92** [comment]
Scusa per il ritardo nella risposta, eliminando tutto e rifacendo tutto adesso funziona

**Comment by jumping2000** [comment]
> Scusa per il ritardo nella risposta, eliminando tutto e rifacendo tutto adesso funziona

ok. chiudo l'issue
