### ISSUE TITLE
Enhancement - 

### ISSUE THREAD

**Issue by Bobsilvio** [jumping2000/ha-packages#6]
### Package name

Card asciugatrice

### Description

Buongiorno, inanzitutto complimenti per il lavoro.
Alcuni suggerimenti da utente normale.
La guida è ben fatta, ho gia segnalato la questione del TAG_O2 con TAG_02(risolta vedo), indicare anche che sono 3 le sostituizioni ad oggi da fare(cosi uno non si sbaglia).

Consiglierei anche di sistemare il comando con il piu semplice(senza usare root nel terminale)
` chmod 744 /config/packages/autoconfig_x86_64/auto_config.py
python /config/packages/autoconfig_x86_64/auto_config.py -v`
in alternativa il comando è ok, ma si deve aggiungere un cd /config/packages

Suggerimenti:
- aggiungere consumo degli ultimi 7 giorni nelle info (cliccabile)
Sarebbe carino avere delle opzioni dove attivare e disattivare le notifiche alexa, google.. e sopratutto dei messaggi personalizzati da attivare(fine lavaggio..stendi i panni..) (sopratutto sulla lavatrice), mia moglie per esempio vuole la notifica della lavatrice quando fa il risciacquo(bah, cose da donne)

La stessa card si potrebbe utilizzare per lavatrice e lavastoviglie (opzione blueprint, chiamandola con un nome generico la card, o nella guida farla rinominare a seconda della card).

Grazie ancora

### Additional Details

- [ ] I'd like to help developing this feature/improvement.

**Comment by Bobsilvio** [comment]
Dimenticavo, i package, hanno un problema, bisogna eliminare gli spazi (2) prima di homeassistant: e customize:

**Comment by jumping2000** [comment]
> Dimenticavo, i package, hanno un problema, bisogna eliminare gli spazi (2) prima di homeassistant: e customize:

Sei il primo che segnala questa cosa e i package relativi agli elettrodomestici sono qui da un bel po', se qualcun'altro aveva questo errore l'avrebbe sicuramente segnalato. La verifico ma mi sembra molto strano.

**Comment by jumping2000** [comment]
> Buongiorno, inanzitutto complimenti per il lavoro. Alcuni suggerimenti da utente normale. La guida è ben fatta, ho gia segnalato la questione del TAG_O2 con TAG_02(risolta vedo), indicare anche che sono 3 le sostituizioni ad oggi da fare(cosi uno non si sbaglia).

Con la nuova versione ci sarò uno script "evoluto" che farà tutte le sostituzioni necessarie.

> Consiglierei anche di sistemare il comando con il piu semplice(senza usare root nel terminale) ` chmod 744 /config/packages/autoconfig_x86_64/auto_config.py python /config/packages/autoconfig_x86_64/auto_config.py -v` in alternativa il comando è ok, ma si deve aggiungere un cd /config/packages

La soluzione indicata è generica e funziona con tutte le installazioni di HA, cioè HAOS, HA Container, HA Supervised e HA Core.  
E in alcune installazioni potrebbe essere necessario il root.

> Suggerimenti:
> 
> * aggiungere consumo degli ultimi 7 giorni nelle info (cliccabile)

Ci sono i consumi settimanali (lun-dom), non prevedo di evidenziare i consumi degli ultimi 7 giorni

>   Sarebbe carino avere delle opzioni dove attivare e disattivare le notifiche alexa, google.. e sopratutto dei messaggi personalizzati da attivare(fine lavaggio..stendi i panni..) (sopratutto sulla lavatrice), mia moglie per esempio vuole la notifica della lavatrice quando fa il risciacquo(bah, cose da donne)

Questo lo fai nel blueprint, puoi scegliere quali notifiche attivare 
 
> La stessa card si potrebbe utilizzare per lavatrice e lavastoviglie (opzione blueprint, chiamandola con un nome generico la card, o nella guida farla rinominare a seconda della card).

Ci sono già le card per asciugatrice/lavatrice/forno/lavastoviglie, per gli ultimi tre uscira la versione analoga a quella dell'asciugatrice quindi completamente automatizzata

**Comment by Bobsilvio** [comment]
> > Dimenticavo, i package, hanno un problema, bisogna eliminare gli spazi (2) prima di homeassistant: e customize:
> 
> Sei il primo che segnala questa cosa e i package relativi agli elettrodomestici sono qui da un bel po', se qualcun'altro aveva questo errore l'avrebbe sicuramente segnalato. La verifico ma mi sembra molto strano.

Ok, nel mio caso dava problemi, duplicazione name

**Comment by jumping2000** [comment]
> > > Dimenticavo, i package, hanno un problema, bisogna eliminare gli spazi (2) prima di homeassistant: e customize:
> > 
> > 
> > Sei il primo che segnala questa cosa e i package relativi agli elettrodomestici sono qui da un bel po', se qualcun'altro aveva questo errore l'avrebbe sicuramente segnalato. La verifico ma mi sembra molto strano.
> 
> Ok, nel mio caso dava problemi, duplicazione name

La duplicazione del nome non riguarda l'indentatura o gli spazi:
è dovuta al fatto che ogni package pubblicato ha una entità  input_number corrispondente al costo al kwh dell'energia. 
Quindi se utilizzo solo il package asciugatrice non ho nessun problema ma se uso il package asciugatrice e quello lavatrice, avrò la stessa entità in due package e quindi va tolto da uno dei 2.

**Comment by Bobsilvio** [comment]
Io ho solo uno al momento, che ha funzionato per un pò, poi al riavvio mi ha dato questo:
<img width="1166" alt="Screenshot 2023-10-13 alle 20 29 44" src="https://github.com/jumping2000/ha-packages/assets/814211/15b62367-3fcd-4a9d-bcf9-8a20769080b6">

**Comment by jumping2000** [comment]
> Io ho solo uno al momento, che ha funzionato per un pò, poi al riavvio mi ha dato questo: <img alt="Screenshot 2023-10-13 alle 20 29 44" width="1166" src="https://user-images.githubusercontent.com/814211/275006840-15b62367-3fcd-4a9d-bcf9-8a20769080b6.png">

sensor.asciugatrice_cost dipende da input_number.costo_energia, dovresti vedere che valore hai in queste entità- cmq l'errore dovrebbe essere legato a quello precedente cioè alla duplicazione di nomi, probabilmente hai già un costo_energia da qualche parte

**Comment by jumping2000** [comment]
Nothing to do
